name: Update Jobs Daily
on:
  schedule:
    # 05:00 UTC = 06:00 France | 18:00 UTC = 19:00 France
    - cron: '0 5,18 * * *' 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:      
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Run Scraper
        run: |
          mkdir -p data
          python scraper_reel.py
        
      - name: Commit and Push
        run: |
          git config --global user.name 'JobBot'
          git config --global user.email 'bot@jobhub.com'
    
          TIMESTAMP=$(date +"%d-%m-%Y %H:%M")
          
          git pull origin main --rebase || echo "No changes to pull"

          if [ -f "data/jobs.csv" ]; then
            git add data/jobs.csv
            
            # Esto actualizará la fecha de modificación del commit en el repo
            git commit --allow-empty -m "Auto-update & Heartbeat: $TIMESTAMP"
            
            git push origin main
          else
            echo "Error: data/jobs.csv no encontrado"
            exit 1
          fi